require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Product = require('../models/Product');
const Category = require('../models/Category');

const updates = [
  // ============ FASHION - ACCESSORIES ============
  {
    id: '6a3e5637d7d1bdfe68183ec7',
    description: `The Carhartt Acrylic Rib-Knit Beanie is a cold-weather essential that combines classic Carhartt durability with everyday comfort. Made from 100% acrylic rib-knit fabric, it offers reliable warmth without the itchiness of wool. The iconic woven Carhartt label on the front adds a touch of heritage style that's recognizable from a distance.\n\nDesigned to fit most head sizes, the one-size-fits-most construction features a stretchy ribbed knit that conforms comfortably without feeling too tight. The cuffed design lets you adjust the length to your preference—wear it folded for a classic look or pulled down for extra ear coverage on particularly cold days.\n\nAvailable in a wide range of colors from understated neutrals to bold statement shades, this beanie pairs equally well with a work jacket or a casual weekend outfit. It's the kind of no-fuss accessory that earns a permanent spot by the door once temperatures drop, delivering dependable warmth season after season without breaking the bank.`
  },
  {
    id: '6a3e5637d7d1bdfe68183ec8',
    description: `The Columbia Bora Bora Booney Sun Hat is engineered for all-day outdoor protection with Omni-Shade UPF 50 fabric that blocks harmful UVA and UVB rays. The 3-inch brim provides generous shade for your face, ears, and neck, making it ideal for fishing, hiking, gardening, or any activity that puts you under the sun for extended periods.\n\nComfort features include an Omni-Wick sweatband that pulls moisture away from your forehead to keep you dry, and a ventilated mesh panel that promotes airflow to prevent overheating. The adjustable chin strap ensures the hat stays put in windy conditions, while the toggle closure at the back lets you fine-tune the fit.\n\nLightweight and packable, the Bora Bora Booney won't weigh you down on long treks and can be stuffed into a backpack without losing its shape. Whether you're spending a day on the water or working in the yard, this hat delivers the kind of reliable sun protection that lets you focus on the activity rather than squinting into the glare.`
  },
  {
    id: '6a3e5637d7d1bdfe68183ec9',
    description: `The Fossil RFID Leather Belt is crafted from genuine leather with a brushed nickel buckle that gives it a clean, polished look suitable for both dress and casual wear. The reversible design effectively gives you two belts in one—flip it over to switch between two complementary finishes without changing belts.\n\nBuilt-in RFID blocking technology protects the cards stored in the hidden wallet compartment from electronic pickpocketing, adding a layer of security that goes beyond style. The classic width fits standard belt loops on most jeans, chinos, and dress pants, making it a versatile addition to any wardrobe.\n\nThe leather develops a rich patina over time, giving the belt character that synthetic materials simply can't replicate. Whether you're heading to the office or out for a weekend dinner, the Fossil RFID belt delivers a refined look with practical functionality that makes it a smart everyday choice.`
  },
  {
    id: '6a3e5638d7d1bdfe68183eca',
    description: `The Perry Ellis Dress Socks 3-Pack brings reliable comfort and understated style to your everyday footwear rotation. Made from a breathable cotton blend, these socks wick moisture and allow airflow to keep your feet dry and comfortable throughout long workdays. The crew-length cut sits at mid-calf, providing coverage that looks polished with dress shoes and loafers.\n\nEach pack includes three pairs in assorted colors that coordinate easily with both light and dark footwear. Reinforced heel and toe construction adds durability in the areas that take the most punishment, so these socks hold up wash after wash without thinning out or developing holes.\n\nThe lightweight knit maintains a smooth feel against the skin without the bulk of athletic socks, making them ideal for pairing with suits, slacks, or business casual attire. For anyone tired of socks that pill, fade, or fall apart after a few washes, this Perry Ellis pack offers a dependable upgrade.`
  },
  {
    id: '6a3e5638d7d1bdfe68183ecb',
    description: `The Timberland Billfold Wallet is constructed from fine-edge genuine leather that's been carefully cut and stitched for a clean, refined appearance. The RFID blocking lining protects your credit cards and IDs from digital theft, while the slim billfold profile slips easily into front or back pockets without creating bulk.\n\nInside, you'll find six card slots with staggered pockets that keep cards organized and accessible, along with a clear ID window for quick access to your driver's license. The stretch construction around the edges allows the wallet to expand slightly when fully loaded while maintaining its sleek silhouette.\n\nTimberland's attention to detail shows in the quality of the stitching and the smoothness of the leather, which softens and develops character with daily use. It's the kind of wallet that balances form and function without unnecessary bells and whistles—just solid craftsmanship and a design that works.`
  },
  {
    id: '6a3e5639d7d1bdfe68183ecc',
    description: `The BASICO Infinity Scarf is a versatile accessory that adds warmth and style to any outfit without the bulk of a traditional scarf. The continuous loop design wraps comfortably around your neck in a single motion, eliminating the need to tie, tuck, or adjust throughout the day. Made from a soft knit fabric, it feels gentle against the skin while providing a cozy layer of insulation.\n\nLightweight enough to wear indoors as a fashion statement yet substantial enough to ward off chilly winds, this scarf transitions seamlessly from casual errands to evening outings. The infinity loop stays securely in place without dangling ends that can catch or unravel, making it practical for active lifestyles.\n\nAvailable in multiple colors, the BASICO Infinity Scarf pairs effortlessly with jackets, sweaters, and dresses alike. It's the kind of effortless accessory that elevates a simple outfit with minimal effort, and its compact size means it packs easily into a purse or carry-on when you're on the go.`
  },
  {
    id: '6a3e5639d7d1bdfe68183ecd',
    description: `The Baublebar Mini Alidia Ring Set includes six stackable rings crafted from 14k gold-plated metal with a dainty, minimalist aesthetic that's perfect for everyday wear. The mix-and-match designs range from simple bands to delicate twisted and beaded styles, giving you endless combinations to suit your mood and outfit.\n\nEach ring is nickel-free, making them suitable for sensitive skin that reacts to lower-quality metals. The lightweight construction means you can wear multiple rings simultaneously without the heaviness or discomfort that comes with chunkier jewelry. The 14k gold plating holds up well to daily wear, maintaining its warm luster through regular use.\n\nWhether you're stacking all six on one hand or distributing them across both, the Mini Alidia set offers a polished, put-together look that works from the office to a night out. The set comes beautifully packaged, making it an easy gift for anyone who loves understated, trendy jewelry.`
  },
  {
    id: '6a3e5639d7d1bdfe68183ece',
    description: `The HAOLOTA Cat Eye Sunglasses bring vintage glamour to modern eyewear with their oversized cat-eye silhouette and polarized lenses. The UV400 protection blocks 100% of harmful UVA and UVB rays, keeping your eyes safe while you look effortlessly stylish. The polarized lenses eliminate glare from reflective surfaces like water, pavement, and car hoods, making them ideal for driving and outdoor activities.\n\nLightweight frames keep the glasses comfortable for extended wear, and the multiple color options let you match your sunglasses to your personal style. The cat-eye shape flatters a variety of face shapes, adding a touch of retro sophistication that never goes out of fashion.\n\nWhether you're lounging at the beach, running errands, or adding a finishing touch to a summer outfit, these sunglasses deliver both function and fashion at an accessible price point. They're the kind of accessory that instantly elevates a look without trying too hard.`
  },
  {
    id: '6a3e563ad7d1bdfe68183ecf',
    description: `The Kate Spade Staci Cardholder is crafted from signature Saffiano leather, known for its cross-hatch texture that resists scratches and maintains a polished appearance over time. The compact design features four card slots for essentials like your ID, credit cards, and transit pass, along with a center compartment that's perfect for folding cash or storing receipts.\n\nA removable wristlet strap adds versatility, letting you carry the cardholder on its own as a minimalist clutch for quick errands or attach it to a larger bag for easy access. The sleek profile slips effortlessly into pockets, clutches, and small bags without adding bulk.\n\nKate Spade's playful yet sophisticated design aesthetic shines through in the clean lines and quality construction of the Staci cardholder. It's the kind of everyday accessory that proves you don't need a large wallet to stay organized and stylish.`
  },
  {
    id: '6a3e563ad7d1bdfe68183ed0',
    description: `The Vera Bradley Reactive Tote Bag is made from Lighten Up fabric that's both lightweight and water-repellent, keeping your belongings dry during unexpected rain showers. The spacious interior includes a padded laptop sleeve that fits devices up to 15 inches, along with multiple organizational pockets for your phone, keys, wallet, and other essentials.\n\nA full zippered closure keeps everything secure, while the comfortable shoulder straps distribute weight evenly to reduce strain during long days. The material wipes clean easily, making this tote practical for everyday use in all kinds of weather conditions.\n\nAvailable in a variety of patterns and colors, the Reactive Tote transitions seamlessly from work to weekend. It's large enough to carry everything you need for a full day yet lightweight enough that it doesn't feel burdensome, making it a go-to bag for commuters, students, and travelers alike.`
  },
  // ============ FASHION - CLOTHING ============
  {
    id: '6a3e563bd7d1bdfe68183ed3',
    description: `The Amazon Essentials Oxford Shirt delivers the classic button-down look in a slim-fit silhouette that's tailored enough for the office yet relaxed enough for weekend wear. Made from 100% cotton, the fabric feels soft against the skin while maintaining a crisp, structured appearance throughout the day. The wrinkle-resistant finish means you can pull it from the dryer and wear it without reaching for an iron.\n\nThe button-down collar stays neatly in place without looking stiff, and the long sleeves can be rolled up for a more casual vibe. Dual chest pockets add a touch of traditional oxford styling, and the machine-washable construction makes care effortless—no dry cleaning or special handling required.\n\nAvailable in a range of solid colors and patterns, this oxford shirt layers comfortably under blazers and sweaters or stands on its own paired with chinos or jeans. It's the kind of wardrobe staple that earns its keep through versatility, looking equally appropriate at a Monday morning meeting or a Friday night dinner.`
  },
  {
    id: '6a3e563cd7d1bdfe68183ed4',
    description: `The Dockers Alpha Khaki Pants are a straight-fit essential built with stretch fabric and Comfort Flex waist technology that moves with you instead of against you. The wrinkle-free treatment keeps a clean, pressed look throughout the day, whether you're sitting through meetings or traveling. The tapered leg creates a modern silhouette that pairs well with both sneakers and dress shoes.\n\nAvailable in a wide range of colors, these khakis are designed to be the most versatile pants in your closet. The fabric has enough structure to look polished while still feeling comfortable enough for all-day wear. The deep pockets provide practical storage without adding bulk to the hip area.\n\nDockers designed the Alpha Khaki with the modern man in mind—someone who needs pants that transition from a business casual office to a weekend outing without missing a beat. The Comfort Flex waistband is a subtle detail that makes a big difference in daily comfort, especially during long days when a rigid waistband becomes noticeable.`
  },
  {
    id: '6a3e563cd7d1bdfe68183ed5',
    description: `The Hanes EcoSmart Pullover Hoodie is made from a 50/50 cotton-polyester blend that combines the softness of cotton with the durability and shape retention of polyester. The fleece lining provides cozy warmth on cool days, while the kangaroo pocket at the front offers a convenient place to warm your hands or stash your phone and keys.\n\nRibbed cuffs and hem help the hoodie retain its shape wash after wash, preventing the stretched-out look that plagues cheaper alternatives. The tag-free design eliminates the irritation that comes with sewn-in labels, making it comfortable enough for all-day wear. The pull-over style with a drawstring hood lets you adjust the fit to your liking.\n\nWhether you're layering it under a jacket on cold mornings or wearing it solo for a relaxed weekend look, this Hanes hoodie delivers dependable comfort at a price that makes it easy to stock up in multiple colors. The EcoSmart construction also means you're choosing a product made with recycled materials, which is a nice bonus.`
  },
  {
    id: '6a3e563dd7d1bdfe68183ed6',
    description: `The Under Armour UA Tech 2.0 T-Shirt is engineered with UA Tech fabric that feels incredibly soft while wicking sweat and drying rapidly during intense workouts. The 4-way stretch material moves freely in every direction, so it never restricts your range of motion whether you're lifting weights, running, or practicing yoga. The loose fit provides a relaxed, comfortable feel without being baggy.\n\nAnti-odor technology prevents the growth of odor-causing bacteria, keeping the shirt fresher for longer between washes. The lightweight construction means you barely notice you're wearing it, which is exactly what you want from a performance tee. Flatlock seams reduce chafing during repetitive movements.\n\nAvailable in a wide array of colors, the UA Tech 2.0 works just as well for casual everyday wear as it does for the gym. The breathable fabric keeps you cool when things heat up, and the durable construction holds up to regular training without losing its shape or softness. It's a reliable, no-nonsense performance shirt that does its job well.`
  },
  {
    id: '6a3e563dd7d1bdfe68183ed7',
    description: `The Wrangler Authentics Classic Jean features a regular fit that sits comfortably at the waist with room through the seat and thigh before tapering to a modern leg opening. The 5-pocket styling follows the timeless denim blueprint, with a coin pocket, two front pockets, and two back pockets for everyday carry essentials. The Comfort Flex waistband moves with your body for all-day comfort.\n\nMade from stretch denim that recovers its shape after every wear, these jeans maintain their fit and appearance throughout the day without bagging out at the knees. The classic Wrangler construction uses durable stitching and quality hardware that holds up to regular washing and wearing.\n\nWhether you're pairing them with boots for a weekend outing or dressing them up with a button-down for a casual Friday, these Wrangler jeans deliver that authentic denim look and feel that's been trusted for generations. The affordable price point makes it easy to stock up in multiple washes for different occasions.`
  },
  {
    id: '6a3e563ed7d1bdfe68183ed8',
    description: `The Amazon Essentials Women's T-Shirt 2-Pack delivers everyday basics in a classic fit that's neither too tight nor too loose. Made from soft cotton jersey, these tees feel comfortable against the skin and breathe well in warm weather. The crew neck and short sleeve design make them versatile layering pieces that work under cardigans, blazers, and jackets, or stand perfectly fine on their own.\n\nThe machine-washable construction means these shirts are built for real life—toss them in with your regular laundry and they come out looking like new. The cotton fabric holds its shape well through multiple wash cycles, maintaining the fit and color you loved when you first tried them on.\n\nAs a value pack, this two-pack makes it easy to refresh your basics drawer without overspending. Available in multiple color combinations, these tees are the kind of reliable, go-to pieces that form the foundation of a well-rounded casual wardrobe.`
  },
  {
    id: '6a3e563ed7d1bdfe68183ed9',
    description: `The Columbia Benton Springs Fleece Jacket is made from MTR filament fleece that delivers lightweight warmth without the weight of traditional jackets. The soft, plush interior feels cozy against the skin, making it comfortable enough to wear directly over a t-shirt on cool mornings or layer under a heavier coat when temperatures really drop.\n\nZippered hand pockets keep your phone, keys, and wallet secure while you're on the move, and the full-zip design lets you regulate your temperature quickly as conditions change. The stand-up collar provides additional warmth around the neck without feeling restrictive.\n\nVersatile enough for a morning hike, an evening walk, or a casual day out, the Benton Springs pairs as easily with jeans as it does with hiking pants. The lightweight construction also makes it a great travel layer—it packs down small enough to stow in a daypack and pulls double duty as a pillow on long flights.`
  },
  {
    id: '6a3e563ed7d1bdfe68183eda',
    description: `The GRACE KARIN Summer Midi Dress features a flattering V-neck and sleeveless A-line silhouette that creates a graceful, flowing look perfect for warm-weather occasions. The comfortable fabric drapes beautifully without clinging, offering a relaxed fit that's both elegant and easy to move in. The midi length hits at a universally flattering point that works for both casual and semi-formal settings.\n\nAvailable in multiple patterns ranging from floral prints to solid colors, this dress adapts to various occasions with simple accessory changes. Pair it with sandals and a straw bag for a casual brunch, or dress it up with heels and statement jewelry for a summer wedding or garden party.\n\nThe A-line cut provides a forgiving fit that accommodates different body types comfortably, while the lightweight fabric breathes well on hot days. It's the kind of effortless dress that earns compliments without requiring much thought—just slip it on and you're ready to go.`
  },
  {
    id: '6a3e563fd7d1bdfe68183edb',
    description: `The Levi's 721 High Rise Skinny Jeans sit at the natural waist for a flattering, elongated silhouette that pairs perfectly with cropped tops, tucked-in blouses, and cropped sweaters. Made from stretch denim with authentic Levi's construction, these jeans hug your curves through the hip and thigh before tapering to a sleek skinny leg. The classic 5-pocket styling and button closure follow the blueprint that made Levi's an American icon.\n\nThe stretch fabric moves with you comfortably throughout the day while retaining its shape, so the jeans look as good at the end of a long day as they did when you put them on. The high rise provides secure coverage and a smoothing effect that boosts confidence.\n\nAvailable in a range of washes from light to dark, the 721 is the kind of skinny jean that transitions easily from daytime errands to evening outings. Levi's quality denim means these jeans age beautifully, developing a personalized fade pattern that makes them uniquely yours over time.`
  },
  {
    id: '6a3e563fd7d1bdfe68183edc',
    description: `The VIISHOW Maxi Dress combines comfort and style with its short sleeve design, elastic waist, and flowing floral print fabric. The V-neckline adds a touch of femininity without being too revealing, while the elastic waistband creates a defined silhouette that flatters without constricting. The lightweight material drapes gracefully and moves beautifully as you walk.\n\nAvailable in multiple patterns and colors, this dress works for everything from casual weekend outings to outdoor events and vacations. The short sleeves provide light coverage for air-conditioned restaurants, while the breathable fabric keeps you cool when you're outdoors in the sun.\n\nThe pull-on design makes it effortless to wear, and the machine-washable construction means you can enjoy it without worrying about special care instructions. It's the kind of easy, breezy dress that earns a spot in your regular rotation, delivering style and comfort in equal measure.`
  },
  // ============ FASHION - SHOES ============
  {
    id: '6a3e5640d7d1bdfe68183edf',
    description: `The Clarks Desert Boot Chukka is an icon of casual footwear, featuring a suede upper that develops a rich patina with wear. The natural crepe sole provides cushioned comfort with every step, absorbing impact on hard surfaces while maintaining a distinctive textured look that sets it apart from rubber-soled alternatives. The ankle-height silhouette pairs as comfortably with jeans as it does with chinos.\n\nThe lace-up design allows you to dial in the fit, while the classic two or three-eyelet configuration keeps the look clean and uncluttered. Originally inspired by boots worn by British officers in the Cairo market during World War II, the Desert Boot has remained virtually unchanged for decades—a testament to a design that simply works.\n\nWhether you're dressing up for a casual office environment or adding a touch of sophistication to a weekend outfit, the Clarks Desert Boot delivers timeless style that never feels dated. The suede upper requires minimal break-in time, and the crepe sole provides a surprisingly comfortable ride for a shoe with such a heritage design.`
  },
  {
    id: '6a3e5641d7d1bdfe68183ee0',
    description: `The Nike Air Max 270 features the largest Max Air unit in the Air Max family, delivering plush cushioning that's visible through the translucent heel. The lightweight mesh upper provides breathability and a flexible fit that conforms to your foot's shape, while the rubber outsole delivers durable traction on a variety of surfaces. The lifestyle sneaker design bridges the gap between athletic performance and street-ready style.\n\nThe exaggerated Air unit in the heel absorbs impact with every step, making these sneakers comfortable for all-day wear whether you're walking around the city or standing for extended periods. The foam midsole adds additional responsiveness and energy return, keeping your feet feeling fresh.\n\nAvailable in a wide range of colorways, the Air Max 270 makes a bold statement with its oversized Air bubble and sleek silhouette. The combination of cutting-edge cushioning technology and head-turning design has made it one of Nike's most popular lifestyle sneakers, appealing to sneakerheads and casual wearers alike.`
  },
  {
    id: '6a3e5641d7d1bdfe68183ee1',
    description: `The Rockport Classic Dress Oxford pairs traditional dress shoe styling with modern comfort technology. The leather upper develops a handsome patina over time, while the classic lace-up design provides a secure, adjustable fit. The cushioned Ortholite insole absorbs shock and provides all-day comfort, addressing the common complaint that dress shoes sacrifice comfort for style.\n\nThe versatile design works equally well with a business suit, dress slacks, or dark jeans, making it a single shoe that covers a wide range of dress codes. The durable outsole provides reliable traction on both carpeted office floors and wet sidewalks.\n\nFor professionals who spend long hours on their feet—whether in meetings, at conferences, or navigating airport terminals—the Rockport Classic Dress Oxford offers the rare combination of polished appearance and genuine walking comfort. It's the shoe that lets you look professional without dreading the walk from the parking garage.`
  },
  {
    id: '6a3e5642d7d1bdfe68183ee2',
    description: `The Skechers Go Walk 7 Slip-On features Goga Mat insole technology that provides responsive cushioning with every step, mimicking the feel of a yoga mat underfoot. The lightweight construction means your feet stay energized throughout the day without the fatigue that comes from heavier shoes. The slip-on design with dual stretch panels makes getting in and out effortless.\n\nMachine washable construction is a standout feature—simply toss them in the washing machine and air dry for a refresh that extends the life and freshness of the shoe. The responsive cushioning returns energy with each stride, making these comfortable enough for all-day wear during travel, shopping, or casual outings.\n\nAvailable in multiple colors, the Go Walk 7 is the kind of shoe that becomes your default choice for anything that doesn't require dress shoes. The clean, understated design works with athleisure, casual, and even smart casual outfits, making them remarkably versatile for a slip-on sneaker.`
  },
  {
    id: '6a3e5642d7d1bdfe68183ee3',
    description: `The Timberland 6-Inch Premium Boot is built from waterproof leather that's been seam-sealed to keep your feet dry in wet conditions. The anti-fatigue insole absorbs shock and returns energy, making these boots surprisingly comfortable for extended wear despite their rugged construction. Rustproof hardware—including the eyelets and speed hooks—ensures the lacing system holds up in all weather conditions.\n\nThe iconic styling that made Timberland a cultural staple hasn't changed in decades. The wheat nubuck colorway is instantly recognizable, and the padded collar provides comfortable ankle support. The rubber lug outsole delivers reliable traction on wet, muddy, and uneven surfaces.\n\nOriginally designed for construction workers who needed reliable waterproof boots, the Timberland 6-Inch has transcended its workwear roots to become a fashion icon. Whether you're wearing them for their intended purpose on a job site or as a style statement with jeans and a hoodie, these boots deliver durability and character that improve with age.`
  },
  {
    id: '6a3e5643d7d1bdfe68183ee4',
    description: `The CUSHIONAIRE Lane Cork Sandal features a genuine cork footbed that molds to the shape of your foot over time, creating a custom fit that improves with wear. Adjustable straps allow you to fine-tune the fit across the instep and around the ankle, while the EVA sole provides lightweight, shock-absorbing comfort with each step. The contoured footbed delivers natural arch support that reduces foot fatigue during long days.\n\nAvailable in multiple colors, these sandals pair effortlessly with shorts, skirts, and casual dresses for warm-weather versatility. The cork footbed naturally wicks moisture, keeping your feet dry and comfortable even on the hottest days.\n\nThe combination of arch support, adjustable fit, and premium materials makes the CUSHIONAIRE Lane a step above basic flip-flops and fashion sandals. Whether you're walking through a farmer's market, spending a day at the beach, or just running weekend errands, these sandals provide the support and comfort your feet deserve.`
  },
  {
    id: '6a3e5643d7d1bdfe68183ee5',
    description: `The Skechers D'Lites Fresh Start combines a classic chunky sneaker aesthetic with modern comfort technology. The memory foam insole conforms to the unique contours of your foot, providing personalized cushioning that reduces pressure points during extended wear. The lightweight construction belies the shoe's substantial appearance, so you get the bold look without the heavy feel.\n\nShock-absorbing midsole technology cushions each step, making these sneakers comfortable for walking, standing, and light athletic activities. The lace-up design ensures a secure fit, while the padded collar and tongue prevent rubbing and irritation.\n\nThe chunky silhouette has made a major comeback in recent fashion trends, and the D'Lites Fresh Start captures that retro-inspired look while delivering the comfort that modern wearers expect. Whether you're pairing them with leggings for a casual day out or using them as an everyday walking shoe, they deliver the style and comfort that Skechers fans have come to expect.`
  },
  {
    id: '6a3e5643d7d1bdfe68183ee6',
    description: `The Steve Madden Irenee Heeled Sandal features a sturdy block heel that provides stability and support for comfortable all-day wear. The ankle strap with buckle closure ensures a secure fit while adding an elegant finishing touch to the design. Available in multiple colors, these sandals transition seamlessly from daytime events to evening occasions.\n\nThe block heel distributes your weight more evenly than a stiletto, reducing pressure on the ball of your foot and making it easier to walk confidently on various surfaces. The open-toe design shows off a fresh pedicure while allowing your feet to breathe in warm weather.\n\nWhether you're attending a summer wedding, heading to brunch with friends, or dressing up for a date night, the Irenee Heeled Sandal adds the perfect finishing touch. The clean lines and versatile design work with everything from sundresses to tailored pants, making them a wardrobe essential that you'll reach for repeatedly.`
  },
  {
    id: '6a3e5644d7d1bdfe68183ee7',
    description: `The UGG Classic Mini Boot features twinface sheepskin that's soft on both the interior and exterior, providing plush warmth without the need for socks. The lightweight design makes these boots easy to pull on and go, while the 5-inch shaft sits just above the ankle for a casual, relaxed look. The soft suede exterior develops a beautiful patina with wear, giving each pair its own unique character.\n\nThe sheepskin lining naturally regulates temperature, keeping your feet warm in cold weather without overheating in milder conditions. The easy pull-on design means no laces or zippers to fuss with—just slide your feet in and you're ready for a quick errand or a cozy day at home.\n\nUGG's Classic Mini has become a go-to comfort shoe that transcends seasons. While they're most associated with fall and winter, the lightweight construction and breathable sheepskin make them comfortable enough for cool spring evenings as well. They're the kind of shoes that become your absolute favorites once you experience the plush comfort firsthand.`
  },
  {
    id: '6a3e5644d7d1bdfe68183ee8',
    description: `The Vionic High Tide II Sandal is designed by podiatrists to provide genuine arch support that goes beyond what most fashion sandals offer. The EVA footbed cradles your foot's natural contours, while the biomechanical heel cup absorbs impact and stabilizes your stride. Adjustable straps allow you to customize the fit across the instep and around the ankle for secure, comfortable wear.\n\nUnlike flat sandals that offer no support, the Vionic High Tide II helps reduce foot fatigue, plantar fasciitis discomfort, and the general aching that comes from unsupported walking. The lightweight construction means you can wear them all day without the heaviness that supportive shoes sometimes carry.\n\nAvailable in multiple colors, these sandals prove that foot health doesn't require sacrificing style. The clean, modern design works for everything from beach days to outdoor dining, making them a practical choice for anyone who needs arch support but refuses to wear orthopedic-looking footwear.`
  },
  // ============ FASHION - WATCHES ============
  {
    id: '6a3e5645d7d1bdfe68183eeb',
    description: `The Casio G-Shock GW-B5600 is a solar-powered digital watch that never needs a battery replacement thanks to Tough Solar technology that converts any light source into energy. Multi-Band 6 atomic timekeeping automatically receives radio signals to adjust the time with precision accuracy, ensuring you're always on time regardless of where you are in the world.\n\nBuilt to G-Shock's legendary standard of toughness, this watch is shock-resistant and water-resistant to 200 meters, making it suitable for swimming, diving, and the most demanding outdoor activities. World time functionality covers 31 time zones across 48 cities, with the ability to swap between home time and world time at the press of a button.\n\nThe classic square design stays true to the original G-Shock aesthetic that's been beloved by military personnel, athletes, and outdoor enthusiasts for decades. The combination of solar power, atomic accuracy, and bombproof durability makes the GW-B5600 one of the most practical watches you can own—a timepiece that essentially takes care of itself.`
  },
  {
    id: '6a3e5646d7d1bdfe68183eec',
    description: `The Citizen Eco-Drive Chandler BM8180 harnesses light from any source—natural or artificial—to power itself indefinitely, eliminating the need for battery replacements. Citizen's Eco-Drive technology has proven itself over decades, and the Chandler puts it in a rugged, military-inspired stainless steel case that's built for everyday wear. The day and date display at 3 o'clock adds practical functionality.\n\nWater-resistant to 100 meters, the Chandler handles rain, splashes, and recreational swimming without concern. The clean dial design with luminous hands and markers ensures readability in low-light conditions, while the mineral crystal face resists everyday scratches.\n\nThe Chandler embodies Citizen's philosophy of making reliable, environmentally conscious timepieces accessible to everyone. The Eco-Drive movement is accurate and virtually maintenance-free, and the versatile design works equally well with a casual weekend outfit or a more polished weekday look. It's the kind of watch you put on in the morning and forget about—until someone compliments it.`
  },
  {
    id: '6a3e5646d7d1bdfe68183eed',
    description: `The Fossil Grant Chronograph combines classic watchmaking aesthetics with modern functionality. The leather strap develops a rich patina over time, conforming to your wrist for a comfortable, personalized fit. The chronograph subdials add visual interest and stopwatch functionality, while the date window at 4 o'clock provides daily utility.\n\nThe 44mm case strikes a balance between making a statement and remaining wearable for everyday use. Mineral crystal protects the dial from scratches and impacts, while the detailed watch face with its multiple subdials and indices creates a sophisticated, multi-layered look that draws the eye.\n\nFossil's Grant Chronograph appeals to those who appreciate the look of a luxury timepiece without the luxury price tag. The combination of the leather strap, detailed dial, and chronograph functionality creates a watch that looks significantly more expensive than it is, making it an excellent choice for those building their watch collection or looking for a reliable everyday timepiece with character.`
  },
  {
    id: '6a3e5647d7d1bdfe68183eee',
    description: `The Seiko 5 Automatic SNKL23 features a self-winding mechanical movement that powers itself through the natural motion of your wrist, eliminating the need for batteries entirely. The exhibition caseback reveals the intricate inner workings of the movement, offering a window into the mechanical craftsmanship that makes automatic watches so fascinating. The day and date display adds practical daily functionality.\n\nBuilt with a stainless steel case and bracelet, the SNKL23 carries a 100-meter water resistance rating that makes it suitable for swimming and recreational water activities. The classic dress watch design with its clean dial and slim profile pairs effortlessly with both business attire and casual wear.\n\nSeiko's reputation for producing high-quality mechanical watches at accessible price points is well-earned, and the SNKL23 is a perfect example. The automatic movement is reliable and accurate, the build quality exceeds expectations at its price range, and the exhibition caseback adds a touch of watchmaking appreciation that collectors and enthusiasts appreciate. It's an excellent entry point into the world of mechanical watches.`
  },
  {
    id: '6a3e5647d7d1bdfe68183eef',
    description: `The Timex Expedition T49905 features the signature Indiglo night-light that illuminates the entire dial with a soft, even glow at the press of a crown. The rugged metal case stands up to outdoor adventures, while the leather strap adds a classic touch that works for both trail and town. Military time display provides quick 24-hour reading for those who prefer that format.\n\nWater-resistant construction means you can wear this watch in the rain, while washing hands, or during light water activities without concern. The reliable quartz movement keeps accurate time, and the clearly marked dial with luminous hands ensures readability in various lighting conditions.\n\nTimex has been making durable, affordable watches for generations, and the Expedition line embodies that heritage. The Indiglo feature alone makes this watch practical for camping trips, early morning runs, and late-night activities where checking a phone is inconvenient. It's a straightforward, dependable timeproof that delivers exactly what you need without unnecessary complications.`
  },
  {
    id: '6a3e5648d7d1bdfe68183ef0',
    description: `The Citizen Eco-Drive Axiom Women's watch brings minimalist elegance to everyday timekeeping. The clean dial features a single diamond accent at the 12 o'clock position, adding a subtle sparkle without overwhelming the refined design. Citizen's Eco-Drive technology powers the watch using any light source, so it never needs a battery replacement.\n\nThe 27mm case size is proportioned beautifully for smaller wrists, and the leather strap provides a comfortable, classic look that works for both professional and casual settings. The date window adds practical functionality without cluttering the dial.\n\nThe Axiom embodies the less-is-more philosophy, appealing to women who prefer understated sophistication over flashy accessories. The combination of the diamond accent, Eco-Drive convenience, and timeless design makes it a versatile piece that transitions effortlessly from the boardroom to dinner.`
  },
  {
    id: '6a3e5648d7d1bdfe68183ef1',
    description: `The Fossil Carlie Mini Women's watch features a delicate three-hand design in a 36mm case that sits elegantly on the wrist. The stainless steel adjustable bracelet provides a secure, comfortable fit while adding a polished finish to the overall look. Mineral crystal protects the dial from everyday scratches and impacts.\n\nThe clean dial design with its refined indices and hands creates a sophisticated appearance that works for everything from office wear to evening occasions. The adjustable bracelet accommodates a range of wrist sizes, and the deployment clasp ensures the watch stays securely fastened.\n\nFossil's Carlie Mini appeals to those who prefer a watch that complements rather than dominates their look. The smaller case size and delicate proportions make it particularly well-suited for petite wrists, while the stainless steel construction ensures durability and a timeless appearance that doesn't go out of style.`
  },
  {
    id: '6a3e5648d7d1bdfe68183ef2',
    description: `The Invicta Pro Diver Women's watch features a crystal-acented bezel that catches the light beautifully, adding glamour to a sport-inspired design. The 18k ion-plated construction provides a luxurious gold-tone finish that resists tarnishing and maintains its luster through daily wear. The reliable quartz movement keeps accurate time without the maintenance of mechanical alternatives.\n\nWater-resistant to 100 meters, the Pro Diver handles swimming, snorkeling, and recreational water activities with ease. The rotating bezel, while primarily decorative on this model, adds the distinctive diver's watch aesthetic that's been a staple of casual and sporty style for decades.\n\nInvicta has built a following by offering bold, eye-catching watches at accessible price points, and the Pro Diver Women's model exemplifies that approach. The combination of the crystal bezel, gold-tone finish, and sporty silhouette creates a versatile watch that adds a statement to both casual and dressy outfits.`
  },
  {
    id: '6a3e5649d7d1bdfe68183ef3',
    description: `The Michael Kors MK2740 Women's watch makes a statement with a crystal-encrusted bezel that sparkles with every movement of your wrist. The stainless steel case and bracelet provide durability and a polished appearance, while the quartz movement ensures reliable, accurate timekeeping. The date window adds everyday functionality to the glamorous design.\n\nThe 39mm case size creates a bold presence on the wrist that's trendy and eye-catching without being overwhelmingly large. The adjustable bracelet accommodates various wrist sizes, and the mineral crystal face resists everyday scratches to keep the watch looking pristine.\n\nMichael Kors understands that a watch is as much jewelry as it is timepiece, and the MK2740 delivers on both fronts. The crystal bezel elevates the design beyond a standard stainless steel watch, making it appropriate for evening events and special occasions while remaining versatile enough for daily wear. It's the kind of accessory that draws compliments wherever you go.`
  },
  {
    id: '6a3e5649d7d1bdfe68183ef4',
    description: `The SEIKO Quartz SWR085P1 Ladies' watch features a captivating blue dial that shifts in tone depending on the light, creating a mesmerizing visual effect. The quartz movement delivers precise timekeeping with the reliability that Seiko has built their reputation on. The stainless steel bracelet provides a comfortable, secure fit while maintaining a polished, elegant appearance.\n\nThe slim profile sits close to the wrist, making it comfortable for all-day wear and easy to slip under shirt cuffs. The clean dial design with its refined indices and hands keeps the look elegant and uncluttered, while the blue color adds a distinctive personality that sets it apart from standard silver or white dials.\n\nSeiko's attention to detail is evident in the quality of the finishing, the smoothness of the bracelet links, and the clarity of the dial. This is a watch that bridges the gap between everyday timekeeping and dressy accessory, working as well with a business suit as it does with a cocktail dress. It's refined without being pretentious, stylish without being trendy.`
  },
  // ============ SPORTS AND OUTDOORS ============
  {
    id: '6a3e1756282c4f7fe8ad58ee',
    description: `The Adidas Tiro 21 Track Jacket is engineered with AEROREADY moisture-wicking technology that keeps you dry and comfortable during intense training sessions. Made from Primegreen recycled polyester, this jacket delivers performance while supporting sustainability—no virgin polyester is used in its construction. The full-zip design with a stand-up collar provides adjustable coverage and protection from the elements.\n\nZippered side pockets keep your phone, keys, and other essentials secure while you're on the move, and the slim fit creates a streamlined silhouette that looks sharp both on and off the field. The articulated sleeves allow a full range of motion, making it ideal for warm-ups, cool-downs, and everyday athletic wear.\n\nThe Tiro line has been a staple in soccer culture for years, and the 21 version continues that tradition with modern materials and a refined fit. Whether you're heading to practice, watching from the stands, or just running errands, this track jacket delivers the athletic style and functional performance that adidas is known for.`
  },
  {
    id: '6a3e1757282c4f7fe8ad58ef',
    description: `The Coleman 6-Person Cabin Tent is designed with a WeatherTec system that uses welded floors and inverted seams to keep water out, ensuring you stay dry even during unexpected downpours. The generous 10x9-foot interior comfortably fits two queen air beds, making it spacious enough for families or groups of friends. Setup takes approximately 60 seconds with the pre-attached poles and continuous pole sleeves.\n\nA vented rainfly provides additional weather protection while promoting airflow to reduce condensation buildup inside the tent. The double-thick fabric on the floor and walls resists wear and tear from rough terrain, and the large windows let in plenty of natural light while keeping bugs out.\n\nColeman has been making reliable camping gear for over a century, and this 6-person cabin tent reflects that experience. The combination of quick setup, weather protection, and livable space makes it an excellent choice for family camping trips, festivals, and weekend getaways where comfort and convenience matter.`
  },
  {
    id: '6a3e1757282c4f7fe8ad58f0',
    description: `The Hydro Flask 32oz Wide Mouth is built from professional-grade stainless steel with TempShield double-wall vacuum insulation that keeps drinks cold for up to 24 hours and hot for up to 12 hours. The wide mouth opening accommodates standard ice cubes and makes cleaning effortless, while the BPA-free construction ensures no unwanted flavors or chemicals leach into your beverages.\n\nThe leakproof design means you can toss this bottle in a bag without worrying about spills, and the durable powder-coated exterior resists condensation and provides a secure grip even with wet hands. The 32-ounce capacity is ideal for staying hydrated throughout a full day of outdoor activities.\n\nHydro Flask has become synonymous with premium insulated water bottles, and for good reason. The temperature retention is genuinely impressive—you'll still have ice-cold water after a full day in the sun. The wide range of colors and sizes makes it easy to find one that matches your style, and the lifetime warranty speaks to the company's confidence in their product's durability.`
  },
  {
    id: '6a3e1757282c4f7fe8ad58f1',
    description: `The Intex Challenger K1 is an inflatable kayak designed for recreational paddling on lakes and calm rivers. At 9 feet long with a 220-pound weight capacity, it provides a stable, comfortable platform for solo paddlers. The package includes a paddle and hand pump, so you have everything needed to get on the water right out of the box.\n\nThe I-beam floor construction provides rigidity and stability that inflatable kayaks of the past couldn't match, while the adjustable seat with a backrest keeps you comfortable during extended paddling sessions. The inflatable chambers are made from durable vinyl that resists punctures and abrasions.\n\nFor kayaking newcomers or occasional paddlers who don't want to invest in a hard-shell kayak, the Challenger K1 offers an affordable entry point that stores compactly in a closet or car trunk when not in use. It's a fun, accessible way to explore local waterways without the storage and transportation challenges of a traditional kayak.`
  },
  {
    id: '6a3e1757282c4f7fe8ad58f2',
    description: `The Osprey Stratos 24L is a hiking daypack built with an Airspeed ventilated backpanel that creates a gap between the pack and your back, promoting continuous airflow to keep you cool and dry on the trail. The included raincover stows in a dedicated pocket and deploys quickly when unexpected weather rolls in, protecting your gear from the elements. The Stow-on-the-Go attachment lets you secure and access trekking poles without removing the pack.\n\nMultiple pockets and compartments keep your gear organized and accessible, including a stretch mesh front pocket for jackets and a hipbelt pocket for snacks and small essentials. The 24-liter capacity is ideal for day hikes, providing enough room for water, food, extra layers, and safety equipment.\n\nOsprey's attention to ergonomic design shows in the padded hipbelt and shoulder straps that distribute weight evenly across your body. The trekking pole attachment points are positioned for natural arm swing while hiking, and the overall fit adjusts easily to accommodate different body types. It's a thoughtfully designed daypack that makes long hikes more comfortable.`
  },
  {
    id: '6a3e1758282c4f7fe8ad58f3',
    description: `The CAP Barbell 150lb Dumbbell Set includes pairs of 5, 10, 15, 20, and 25-pound dumbbells with rubber hex heads that protect floors and reduce noise during workouts. The knurled handles provide a secure, comfortable grip even when your hands are sweaty, and the anti-roll hex design prevents the dumbbells from rolling away between sets. The A-frame rack keeps everything organized and accessible.\n\nThe rubber coating on the hex heads absorbs impact when you set the weights down, preventing damage to hardwood floors, tiles, and gym mats. The variety of weights covers everything from high-repetition toning exercises to heavier strength-building movements, making this set suitable for full-body workouts.\n\nHaving a complete dumbbell set at home eliminates gym membership costs and the time spent traveling to and from a facility. The CAP Barbell set provides a solid foundation for a home gym, with enough weight variety to support progressive training as your strength improves. The included rack keeps your workout space tidy and professional-looking.`
  },
  {
    id: '6a3e1758282c4f7fe8ad58f4',
    description: `The SKLZ Agility Ladder is a 15-foot training tool with 11 adjustable rungs that helps athletes of all levels improve foot speed, coordination, and agility. The heavy-duty plastic rungs withstand repeated use on grass, turf, and gym floors, while the adjustable spacing lets you customize the difficulty level to match your current fitness and progressively increase the challenge.\n\nThe included carry bag makes it easy to transport the ladder to practice fields, gyms, or outdoor training areas. Setting up and breaking down the ladder takes seconds, so you can transition quickly between drills during time-limited practice sessions.\n\nUsed by professional athletes, college teams, and fitness enthusiasts alike, agility ladders are one of the most effective tools for developing quick feet and lateral movement. The SKLZ version offers a good balance of durability, portability, and value, making it a worthwhile investment for anyone serious about improving their athletic performance.`
  },
  {
    id: '6a3e1758282c4f7fe8ad58f5',
    description: `The Wilson US Open Tennis Racket is built with Arc Technology that provides a larger sweet spot for more forgiving shots, making it ideal for intermediate players looking to improve their game. The graphite construction delivers a good balance of power and control without the fatigue that comes from heavier rackets. The 103 square inch head size offers a generous hitting area.\n\nDouble hole technology in the grommet system allows the strings to deflect more on impact, adding power to your shots without requiring excessive swing speed. The racket comes pre-strung and ready to play, saving you the time and expense of a separate stringing job.\n\nWilson has been a dominant force in tennis equipment for decades, and the US Open racket draws on that heritage to deliver a reliable, playable racket at an accessible price. Whether you're stepping onto the court for the first time or returning to the game after a break, this racket provides the performance and forgiveness that helps you enjoy the sport while developing your skills.`
  },
  // ============ TOYS AND GAMES ============
  {
    id: '6a3e1759282c4f7fe8ad58f6',
    description: `The Nerf N-Strike Elite Disruptor features a 6-dart rotating drum that loads quickly and fires with the slam-fire action—hold down the trigger and pump the handle to send darts flying in rapid succession. With an effective range of up to 90 feet, it provides the firepower needed for competitive Nerf battles. Six official Nerf darts are included, so you're ready to play right out of the package.\n\nThe compact, blaster-style design is easy to aim and handle for both kids and adults, making it a versatile choice for family Nerf battles. The rotating drum provides a satisfying visual element as you watch the remaining dart count decrease during heated competitions.\n\nNerf has been the gold standard in foam dart blasters for years, and the Disruptor continues that tradition with reliable performance and satisfying slam-fire action. Whether you're staging backyard battles, office Nerf wars, or just having casual target practice, this blaster delivers consistent, fun performance at a great value.`
  },
  {
    id: '6a3e1759282c4f7fe8ad58f7',
    description: `The Roblox Ninja Legends Playset brings the popular online game to life with collectible figures and detailed accessories that recreate scenes from the game. Each figure features authentic styling that matches its in-game counterpart, making them display-worthy additions to any Roblox fan's collection. The playset includes an exclusive virtual item code that unlocks content in the online game.\n\nThe detailed accessories add play value and display options, letting kids and collectors create their own ninja scenarios or showcase the figures on a shelf. The build quality and attention to detail reflect the passion that Roblox fans have for the game's characters and world.\n\nFor young Roblox enthusiasts, this playset bridges the gap between screen time and physical play, giving them tangible versions of the characters they love. The exclusive virtual item code adds digital value to the physical purchase, making it a double win for fans who want to enhance both their real-world and online Roblox experience.`
  },
  {
    id: '6a3e175a282c4f7fe8ad58f8',
    description: `The Jenga Classic Game features 54 precision-crafted hardwood blocks that test your steady hand and strategic thinking. Players take turns removing one block at a time from the tower and balancing it on top, creating an increasingly precarious structure that demands focus and precision. The game is simple to learn but surprisingly challenging to master.\n\nSuitable for 1 or more players and ages 6 and up, Jenga brings people together across generations. The hardwood blocks have a satisfying weight and smooth finish that makes each move feel deliberate and tactile. No batteries, no complicated rules—just pure, timeless gaming fun.\n\nWhether you're playing at a family gathering, a party, or a quiet evening at home, Jenga creates moments of suspense and laughter that digital games simply can't replicate. The physical tension of removing a block from a wobbly tower creates genuine excitement, and the crash when the tower finally falls is universally entertaining.`
  },
  {
    id: '6a3e175a282c4f7fe8ad58f9',
    description: `Monopoly has been bringing families and friends together around the board for generations with its classic property trading gameplay. Buy, sell, and trade properties, collect rent, and navigate Chance and Community Chest cards as you try to build your real estate empire. The game supports 2 to 6 players, making it perfect for family game nights and gatherings.\n\nThe iconic tokens, colorful game board, and familiar properties like Boardwalk and Park Place create a nostalgic experience that resonates with players of all ages. The combination of strategy and luck means that anyone can win, keeping all players engaged from start to finish.\n\nMonopoly teaches valuable lessons about money management, negotiation, and risk assessment while delivering hours of entertainment. The game's enduring popularity across decades and cultures speaks to its universal appeal—it's the kind of game that creates lasting memories and friendly rivalries that last well beyond the final roll of the dice.`
  },
  {
    id: '6a3e175a282c4f7fe8ad58fa',
    description: `The LEGO 30682 Technic NASA Mars Rover set lets you build a detailed model of the Perseverance rover that's been exploring the surface of Mars. The 159-piece set includes a buildable Ingenuity helicopter companion and a display stand, creating an impressive showcase piece once completed. The Technic elements add mechanical functionality that brings the model to life.\n\nThe set serves as both an engaging building experience and an educational tool that introduces builders to NASA's Mars exploration program. The detailed design captures key features of the actual rover, making it a conversation piece that sparks curiosity about space science and engineering.\n\nLEGO Technic sets appeal to builders who appreciate mechanical detail and functional design, and this NASA Mars Rover set delivers both in an accessible package. Whether you're a space enthusiast, a LEGO collector, or looking for a meaningful gift for a young scientist, this set provides an enjoyable build and an impressive finished model.`
  },
  {
    id: '6a3e175b282c4f7fe8ad58fb',
    description: `The Hot Wheels 20-Car Gift Pack delivers twenty 1:64 scale die-cast vehicles with authentic detailing and the signature Hot Wheels quality that collectors and kids love. Each car features unique designs, colors, and tampos that make every vehicle in the pack distinct. The 1:64 scale is perfectly sized for both play and display.\n\nPackaged in gift-ready packaging, this set makes an impressive present for birthdays, holidays, and special occasions. The variety of vehicles—from sports cars to trucks to fantasy designs—ensures there's something for every taste and preference.\n\nHot Wheels has been igniting kids' imaginations for over 50 years, and this 20-car pack provides an instant collection for new enthusiasts or expands an existing one for seasoned collectors. The die-cast construction withstands crashes, jumps, and countless laps around Hot Wheels tracks, making these cars as durable as they are detailed.`
  },
  {
    id: '6a3e175b282c4f7fe8ad58fc',
    description: `The Osmo Genius Starter Kit transforms your iPad into an interactive learning platform that combines physical play with digital feedback. The kit includes five hands-on games that cover math, spelling, problem-solving, and creative drawing, making learning feel like play. The Osmo Reflector attaches to your iPad's camera to see what's happening on the table in front of the screen.\n\nTangram challenges players to recreate shapes using physical tiles, while Words tests spelling with letter tiles that the system recognizes in real time. Numbers introduces math concepts through tactile, hands-on activities. The games adapt to skill level, providing appropriate challenges for a range of ages.\n\nWhat makes Osmo unique is its ability to bridge the gap between screen time and physical play. Instead of passively watching a screen, kids actively engage with physical manipulatives that the system recognizes and responds to. It's an approach to educational technology that parents can feel good about, combining the engagement of digital games with the cognitive benefits of hands-on learning.`
  }
];

async function updateDescriptions() {
  await connectDB();

  let successCount = 0;
  let failCount = 0;

  for (const item of updates) {
    try {
      const product = await Product.findByIdAndUpdate(
        item.id,
        { description: item.description },
        { new: true }
      );
      if (product) {
        console.log(`✓ Updated: ${product.name}`);
        successCount++;
      } else {
        console.log(`✗ Not found: ${item.id}`);
        failCount++;
      }
    } catch (err) {
      console.error(`✗ Error updating ${item.id}: ${err.message}`);
      failCount++;
    }
  }

  console.log(`\nDone. Success: ${successCount}, Failed: ${failCount}`);
  mongoose.disconnect();
}

updateDescriptions();
